- hosts: SQL
  tasks:
    - name: Test ping
      win_ping:
      
    - name: requet SQL
      win_shell: "Invoke-Sqlcmd -Query "SELECT TOP (1000) [id], [nom], [prenom], [age]  FROM [user].[dbo].[Table_1]" -ServerInstance "WS-SQL\SQLEXPRESS" | Select-Object * -ExcludeProperty ItemArray, Table, RowError, RowState, HasErrors | ConvertTo-Json"
      register: response

    - set_fact:
      ids: "{{ response.stdout|from_json}}"

    - debug:
      var: ids
