- hosts: SQL
  tasks:
    - name: Test ping
      win_ping:
      
    - name: requet SQL
      script: sql.ps1
      register: response

    - name: debug sql
      debug:
        var: response
        
    - name: module ps
      mssql_query:
