- hosts: SQL
  tasks:
    - name: Test ping
      win_ping:
      
    - name: requet SQL
      script: sql.ps1
      register: response

    - set_fact:
      ids: "{{ response.stdout|from_json}}"

    - debug:
      var: ids
